apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhagyashreeinsurance-deploy
  labels:
    app: bhagyashree-insurance-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bhagyashree-insurance-app
  template:
    metadata:
      labels:
        app: bhagyashree-insurance-app
    spec:
      containers:
      - name: bhagyashree-insurance-container
        image: bhagyashreebaddoli/bhagyashreedevopsins:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bhagyashree-np1-service
  labels:
    app: bhagyashree-insurance-app
spec:
  selector:
    app: bhagyashree-insurance-app

  type: NodePort
  ports:
  - nodePort: 31500
    port: 8081
    targetPort: 8081
